### ISSUE TITLE
Numbers in JSON

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#10]
Typically, integers in JavaScript and most JSON implementations are limited to 2^53-1.
This gives problems, as the VLIE values in the QUIC/H3 specs are 2^62-1.

Two options:
- Allow bigger values in the JSON. Tools MUST use a JSON parser that can deal with this and a JavaScript engine that supports BigInt (currently limited to Chromium: https://caniuse.com/#search=bigint)
- Encode all VLIE fields as strings. Tools have to deal with this themselves (most will probably just take the shortcut of assuming actual values will be < 2^53 and just use the JavaScript "Number" type). This is best for a wide tooling implementation area in browsers. 

Currently, the draft uses option 2.

**Comment by jlaine** [comment]
Firefox and Edge (obviously) also suport BigInt according to caniuse. The only significant outlier is Safari.

**Comment by martinthomson** [comment]
An alternative would be to define a completely different interface.

JSON is an odd choice because what generally happens here is that you have a stream of events.  Constructing that as a JSON array is awkward as it interacts poorly with typical JSON processing pipelines.  You might use JSON text sequences, but that is an odd line.

CSV has some nice properties: you define the first column as the event type and remaining fields dependent on the type.  Then each record is delineated by something easy to produce (CRLF) and fields are easily recoverable.  Everything is a string then and you can define processing for number fields.

**Comment by rmarx** [comment]
As pointed out by @marten-seemann, the JSON spec itself does not limit the numbers to 2^53-1, it is just the implementations.

As such, for the purposes of the qlog spec, and if we stay with JSON, we can simply require clients to be able to deal with larger numbers in one of several ways (e.g., either detect and discard, detect and notify user, ignore, use parser that can handle up to 64 bit).

I am thinking of switching to option 1 (from the first post in this issue) for draft-02.
