### ISSUE TITLE
token logging

### ISSUE THREAD

**Issue by marten-seemann** [quiclog/internet-drafts#117]
Currently (in draft-02) tokens are logged like this:
```
    retry_token?:bytes, // only if header.packet_type === retry
    retry_token_length?:uint32, // only if header.packet_type === retry
```

It would be nice if it was possible if the server could also log tokens received on Initial packets. More interesting than the raw byte representation of a token would be the data encoded in a token. The most interesting bit is probably if the token is a Retry token or a NEW_TOKEN token. Implementations could then add more fields and fill them with data that's encoded into the token.

**Comment by rmarx** [comment]
So, this is an absolute mess... but it's a mess in the specs as well. 

Retry (from the server) and stateless reset tokens are logged in the packet events directly, because they are sent in the body of their respective packet types.

Then, tokens included in the initial, are logged in the PacketHeader struct (see https://quiclog.github.io/internet-drafts/draft02/draft-marx-qlog-event-definitions-quic-h3.html#name-packetheader). There is no specified way in the spec to know whether the initial token is retry or NEW_TOKEN, except for the semantics of the connection state at that time, so that's what the current setup is with qlog as well (which, I agree, is suboptimal). 

I -could- add a kind of `token_type?: "retry"|"resumption"` to PacketHeader I guess, but then there will be situations where implementations don't want to log that/don't have that information available at that location etc. 

As for the "what exactly is in a token"... this is hyper implementation-specific, so you couldn't make interoperable tools for that anyway. I considered adding a generic `token_contents:any` field, but given the above I'd have to repeat that for the `retry_token` and PacketHeader:token separately, which is again... a mess. So I'm really not sure about the cleanest solution. 

As explained in https://github.com/quiclog/internet-drafts/issues/94, I was planning on keeping this floating for -02 and probably moving to separate token-based events in -03 to make this cleaner.

**Comment by marten-seemann** [comment]
> Then, tokens included in the initial, are logged in the PacketHeader struct (see https://quiclog.github.io/internet-drafts/draft02/draft-marx-qlog-event-definitions-quic-h3.html#name-packetheader). There is no specified way in the spec to know whether the initial token is retry or NEW_TOKEN, except for the semantics of the connection state at that time, so that's what the current setup is with qlog as well (which, I agree, is suboptimal).

That's not true. An implementation MUST be able to distinguish between them, see https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-token-construction:
> A token sent in a NEW_TOKEN frames or a Retry packet MUST be constructed in a way that allows the server to identify how it was provided to a client. These tokens are carried in the same field, but require different handling from servers.

> As for the "what exactly is in a token"... this is hyper implementation-specific, so you couldn't make interoperable tools for that anyway.
In principle, yes, although the spec imposes a few restrictions:
> Tokens sent in NEW_TOKEN frames MUST include information that allows the server to verify that the client IP address has not changed from when the token was issued.

and
> Servers SHOULD ensure that tokens sent in Retry packets are only accepted for a short time. 

Very likely, implementations will save the creation time and the peer's remote address into the token.

**Comment by rmarx** [comment]
Fixed for draft-02 by extracting out a separate Token class. Open to revisiting this for draft-03.
