### ISSUE TITLE
Consolidate repeated padding frames?

### ISSUE THREAD

**Issue by agrover** [quiclog/internet-drafts#34]
Padding frames contain no information, but when eyeballing a qlog for the start of a connection, they swamp more interesting things.

It's a bit of a cheat, given that qlog otherwise is 1:1 between packet contents and logging, but I was wondering if a more compact representation of repeated padding frames might be nice.

This is less about qlog file size -- I'm assuming repeated padding entries in json would compress amazingly -- more about human readability.

I see pros and cons, but wanted to raise it as an issue. Cheers.

**Comment by rmarx** [comment]
I'm very confused at the moment, because I was sure I had already added this to the editor's draft for version -02, but... apparently not? 

So yes, I definitely think this is a good idea. At one point, Facebook was logging 1 padding frame for each byte of padding and that was horrendous. 

I thought about just adding a "length" field to the padding frame, indicating the amount of bytes padded. Would you agree that's the correct approach?

**Comment by hawkinsw** [comment]
> I'm very confused at the moment, because I was sure I had already added this to the editor's draft for version -02, but... apparently not?
> 
> So yes, I definitely think this is a good idea. At one point, Facebook was logging 1 padding frame for each byte of padding and that was horrendous.
> 
> I thought about just adding a "length" field to the padding frame, indicating the amount of bytes padded. Would you agree that's the correct approach?

That sounds like a pretty good idea to me. It also seems to "mirror" the approach that Wireshark takes?
![Screenshot from 2020-01-15 03-52-38](https://user-images.githubusercontent.com/8715530/72419310-911e2180-374a-11ea-8520-1b8f99a34a12.png)

**Comment by agrover** [comment]
> I thought about just adding a "length" field to the padding frame, indicating the amount of bytes padded. Would you agree that's the correct approach?

Sounds good to me!
