### ISSUE TITLE
QLOGDIR environment variable

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#51]
Maybe the main schema should specify something like SSLKEYLOGFILE that implementations SHOULD adhere to. 

Though it needs to be a directory, not 1 file, since we probably don't want to dump all qlogs into 1 single file as we do with the SSL keys. 

A good option might be QLOGDIR.

We should also specify how to write/name individual files in that directory (or at least list options)

TODO: find out where SSLKEYLOGFILE Is specified exactly (seems a bit difficult to google).

CC @bagder @xquery

**Comment by bagder** [comment]
I don't think `SSLKEYLOGFILE` is specified anywhere and I don't know exactly how it came to exist, but I know that Firefox and Chrome with Wireshark have supported it a fairly long time and curl does too since a while back. It's just very convenient to have several applications agree on how to do this. I would very much like to have curl support the qlog variable as well.

**Comment by LPardue** [comment]
This wfm, I need a parameter to pass to control behaviour anyway and this avoids me having to make my own
