### ISSUE TITLE
relax ordering requirement

### ISSUE THREAD

**Issue by marten-seemann** [quiclog/internet-drafts#66]
The spec currently says:
> Events in each individual trace MUST be logged in strictly ascending timestamp order (though not necessarily absolute value, for the "delta_time" setup). Tools are NOT expected to sort all events on the timestamp before processing them.

This poses problems for multi-threaded implementations that implement a streaming encoder. Since qlogs take up a lot of memory for long-lived / active connections, implementing a streaming encoder is the only way to run qlog in production, without risking to overflow the host's memory.

If you have a multithreaded application, it's not possible to guarantee that the events will be strictly ordered by timestamp.

**Comment by rmarx** [comment]
I've been thinking about this while implementing an automated sort() in qvis to prevent this from going wrong (kazu also had this problem).

In and of itself, it's not necessary to -log- in order I think. But it saves a lot of time in (especially web-based) tooling if you don't have to sort all logs prior to using them. So we could say something like:

> Events SHOULD be logged in ascending timestamp order. Tools are not expected to do sorting. If an implementation cannot guarantee ordered logs, they can use a postprocessing step to order the logs if their tool of choice does not offer automatic sorting.

This is similar to wireshark's approach IIUC (https://www.wireshark.org/docs/wsug_html_chunked/AppToolsreordercap.html)

Though I am not 100% sure that sort() solves all problems... we've had some issues with wireshark recently where packets captured on different interfaces (but ending up in the same pcap) had quite a bit of timestamp differences and re-ordering on the timestamp field would be obviously wrong. Now, this is probably an artifact of the internal tcpdump implementation etc. and QUIC/H3 stacks should be much less affected. However, given that qlog is envisioned as a wider format (and because I can envision people splicing pcap-to-qlog with direct-qlog events from the application), I can't simply dismiss this.

**Comment by marten-seemann** [comment]
The whole point of using a streaming encoder is to not have to load the whole qlog file into memory at the same time. A post-processing step (which would have to happen when the whole qlog is written) would require me to do exactly that, so that's not an option.

**Comment by rmarx** [comment]
I'm thinking more of an offline post-processing step. e.g., either in-bulk by a separate server/process as a cron-job or immediately prior to loading into a tool that doesn't support ordering itself. 

For example, qvis currently detects if traces are un-ordered and does a sort() if that's the case. You could see that as a "post processing step" built in to the tooling itself. This is plenty fast enough for smaller traces (say up to 100MB) but can be slower for larger ones (though those aren't optimal in qvis either way).

I think the whole point will be a bit moot in practice, since I would expect tools to have this built-in in practice, but that doesn't mean I would want to require this in the text. 

Maybe @nibanks has some insight into how windows ETW handles this type of thing?

**Comment by marten-seemann** [comment]
That would be possible, but kind of ugly, since it would mean that a QUIC implementation cannot export semi-valid qlog on its own, and is reliant on external programs to fix the exported data.

**Comment by rmarx** [comment]
So I'm not sure what the solution would be then unless you'd force the tools to sort the logs themselves. Is that what you're advocating for?
