### ISSUE TITLE
PTO is per PN-space

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#69]
Currently, we log `pto_count` in `metrics_updated`. However, we can have multiple PTO's running across multiple PN spaces and there is no proper way to correlate them with a PN space in metrics_updated.

This also impacts the `loss_timer*` event types. 

Possible resolutions:
- Add pn_space attribute to `metrics_updated`
- Split PTO count into a separate event (potentially merge with loss_timer?)

TODO: reason more about how these metrics are tied to PN spaces in general (are there others than PTO that are duplicated)

cc @marten-seemann

**Comment by marten-seemann** [comment]
> * Add pn_space attribute to metrics_updated

Most other metrics in the `metrics_updated` event are independent of the PN space, so that would be weird.

> * Split PTO count into a separate event (potentially merge with loss_timer?)

I'd prefer to do that. Not sure if it makes sense to merge is with the loss timer events, since we also need to be able to log a reset of the PTO count to 0 (which doesn't require setting of a timer).
